all:
	# g++ lib/amx-int8.S  amx_int8_loop.cc -O2 -o amx_int8_loop -march=sapphirerapids
	# g++ lib/amx-bf16.S  amx_bf16_loop.cc -O2 -o amx_bf16_loop -march=sapphirerapids
	# g++ lib/amx-int8.S  amx_int8_matrix.cc -O2 -o amx_int8_matrix -march=sapphirerapids
	g++ lib/amx-bf16.S  amx_bf16_matrix.cc -O2 -o amx_bf16_matrix -march=sapphirerapids
	# g++ amx_tile_cfg_release_bench.cc -O2 -o amx_cfgrelease -march=sapphirerapids

